// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorServer.Models
{
    public partial class Carello
    {
        [Key]
        [Column("idCarello")]
        public int IdCarello { get; set; }
        [Column("idCliente")]
        public int IdCliente { get; set; }
        [Column("idRelazioneNegozioProdotto")]
        public int IdRelazioneNegozioProdotto { get; set; }
        [Column("quantità")]
        public int Quantità { get; set; }

        [ForeignKey("IdCliente")]
        [InverseProperty("Carello")]
        public virtual Cliente IdClienteNavigation { get; set; }
        [ForeignKey("IdRelazioneNegozioProdotto")]
        [InverseProperty("Carello")]
        public virtual RelazioneNegozioProdotto IdRelazioneNegozioProdottoNavigation { get; set; }
    }
}