// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorServer.Models
{
    public partial class Cliente
    {
        public Cliente()
        {
            Carello = new HashSet<Carello>();
        }

        [Key]
        [Column("idCliente")]
        public int IdCliente { get; set; }
        [Required]
        [Column("username")]
        [StringLength(50)]
        [Unicode(false)]
        public string Username { get; set; }
        [Required]
        [Column("password")]
        [StringLength(50)]
        [Unicode(false)]
        public string Password { get; set; }
        [Column("soldiDisponibili", TypeName = "money")]
        public decimal SoldiDisponibili { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Required]
        [Column("cognome")]
        [StringLength(50)]
        [Unicode(false)]
        public string Cognome { get; set; }
        [Required]
        [Column("codiceFiscale")]
        [StringLength(16)]
        [Unicode(false)]
        public string CodiceFiscale { get; set; }
        [Required]
        [Column("cap")]
        [StringLength(5)]
        [Unicode(false)]
        public string Cap { get; set; }
        [Required]
        [Column("città")]
        [StringLength(50)]
        [Unicode(false)]
        public string Città { get; set; }
        [Required]
        [Column("indirizzo")]
        [StringLength(50)]
        [Unicode(false)]
        public string Indirizzo { get; set; }

        [InverseProperty("IdClienteNavigation")]
        public virtual ICollection<Carello> Carello { get; set; }
    }
}