// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorServer.Models
{
    public partial class Dipendente
    {
        public Dipendente()
        {
            NegozioIdDirettoreNavigation = new HashSet<Negozio>();
            NegozioIdResponsabileNavigation = new HashSet<Negozio>();
        }

        [Key]
        [Column("idDipendente")]
        public int IdDipendente { get; set; }
        [Required]
        [Column("username")]
        [StringLength(50)]
        [Unicode(false)]
        public string Username { get; set; }
        [Required]
        [Column("password")]
        [StringLength(50)]
        [Unicode(false)]
        public string Password { get; set; }
        [Column("idNegozio")]
        public int? IdNegozio { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Required]
        [Column("cognome")]
        [StringLength(50)]
        [Unicode(false)]
        public string Cognome { get; set; }
        [Required]
        [Column("codiceFiscale")]
        [StringLength(16)]
        [Unicode(false)]
        public string CodiceFiscale { get; set; }
        [Column("idRuolo")]
        public int? IdRuolo { get; set; }

        [ForeignKey("IdNegozio")]
        [InverseProperty("Dipendente")]
        public virtual Negozio IdNegozioNavigation { get; set; }
        [ForeignKey("IdRuolo")]
        [InverseProperty("Dipendente")]
        public virtual Ruolo IdRuoloNavigation { get; set; }
        [InverseProperty("IdDirettoreNavigation")]
        public virtual ICollection<Negozio> NegozioIdDirettoreNavigation { get; set; }
        [InverseProperty("IdResponsabileNavigation")]
        public virtual ICollection<Negozio> NegozioIdResponsabileNavigation { get; set; }
    }
}