// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorServer.Models
{
    public partial class Negozio
    {
        public Negozio()
        {
            Dipendente = new HashSet<Dipendente>();
            RelazioneNegozioProdotto = new HashSet<RelazioneNegozioProdotto>();
        }

        [Key]
        [Column("idNegozio")]
        public int IdNegozio { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Column("immagine", TypeName = "image")]
        public byte[] Immagine { get; set; }
        [Required]
        [Column("indirizzo")]
        [StringLength(50)]
        [Unicode(false)]
        public string Indirizzo { get; set; }
        [Column("idDirettore")]
        public int IdDirettore { get; set; }
        [Column("idResponsabile")]
        public int IdResponsabile { get; set; }

        [ForeignKey("IdDirettore")]
        [InverseProperty("NegozioIdDirettoreNavigation")]
        public virtual Dipendente IdDirettoreNavigation { get; set; }
        [ForeignKey("IdResponsabile")]
        [InverseProperty("NegozioIdResponsabileNavigation")]
        public virtual Dipendente IdResponsabileNavigation { get; set; }
        [InverseProperty("IdNegozioNavigation")]
        public virtual ICollection<Dipendente> Dipendente { get; set; }
        [InverseProperty("IdNegozioNavigation")]
        public virtual ICollection<RelazioneNegozioProdotto> RelazioneNegozioProdotto { get; set; }
    }
}