// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorServer.Models
{
    public partial class Prodotto
    {
        public Prodotto()
        {
            RelazioneNegozioProdotto = new HashSet<RelazioneNegozioProdotto>();
        }

        [Key]
        [Column("idProdotto")]
        public int IdProdotto { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Column("immagine", TypeName = "image")]
        public byte[] Immagine { get; set; }
        [Required]
        [Column("caratteristiche")]
        [StringLength(1000)]
        [Unicode(false)]
        public string Caratteristiche { get; set; }
        [Required]
        [Column("marca")]
        [StringLength(50)]
        [Unicode(false)]
        public string Marca { get; set; }
        [Column("prezzo", TypeName = "money")]
        public decimal Prezzo { get; set; }

        [InverseProperty("IdProdottoNavigation")]
        public virtual ICollection<RelazioneNegozioProdotto> RelazioneNegozioProdotto { get; set; }
    }
}