// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorServer.Models
{
    public partial class Ruolo
    {
        public Ruolo()
        {
            Dipendente = new HashSet<Dipendente>();
        }

        [Key]
        [Column("idRuolo")]
        public int IdRuolo { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Required]
        [Column("descrizione")]
        [StringLength(1000)]
        [Unicode(false)]
        public string Descrizione { get; set; }

        [InverseProperty("IdRuoloNavigation")]
        public virtual ICollection<Dipendente> Dipendente { get; set; }
    }
}